services:
  postgres:
    container_name: cloudflex_postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: cloudflex_db
      POSTGRES_USER: cloudflex_user
      POSTGRES_PASSWORD: cloudflex_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cloudflex-net

  redis:
    container_name: cloudflex_redis
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - cloudflex-net

volumes:
  postgres_data:

networks:
  cloudflex-net:
    driver: bridge