spring:
  application:
    name: cloudflex-blog

  profiles:
    active: local

  config:
    import:
      - optional:file:.env

  datasource:
    url: jdbc:postgresql://localhost:5432/cloudflex_db
    username: cloudflex_user
    password: cloudflex_pass
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres
      mode: always

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
  servlet:
    context-path: /api

mybatis:
  mapper-locations: "classpath:/mapper/**/*.xml"
  type-aliases-package: com.cloudflex_blog.modules.user.domain.entity, com.cloudflex_blog.modules.post.domain.entity
  configuration:
    map-underscore-to-camel-case: true